#!/bin/sh

set -e

[ -z "$DEBUG" ] || set -x

echo "===> Generate build...\n"

CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o build/c4-portfolio

echo "\n===> Generate image...\n"

docker build --no-cache -t c4-portfolio .

echo "\n===> Docker tag...\n"

docker tag c4-portfolio fernandocagale/c4-portfolio

echo "\n===> Docker push...\n"

docker push fernandocagale/c4-portfolio

echo "\n===> Kubectl apply...\n"

kubectl apply -f kubernetes/c4-portfolio-deployment.yml -n c4

echo "\n===> Kubectl pods...\n"

kubectl get pods -n c4